
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; MODULE      : fontawesome.scm
;; DESCRIPTION : Support for the Fontawesome glyphs collections
;; COPYRIGHT   : (C) 2021 Massimiliano Gubinelli
;;
;; This software falls under the GNU general public license version 3 or later.
;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(texmacs-module (fontawesome))

;; install the fonts
(display "Load Fontawesome fonts in TeXmacs\n")
(font-database-extend-local 
    (url-complete  "$TEXMACS_HOME_PATH/plugins/*/fonts/truetype" "r"))


(define (groups) `(
  (,awesome-brands-dict . "Font Awesome 5 Brands Regular" )
  (,awesome-free-regular-dict . "Font Awesome 5 Free Regular" )
  (,awesome-free-solid-dict . "Font Awesome 5 Free Solid" )))

(define (get-dict group)
  (cond 
    ((== group "brands") awesome-brands-dict)
    ((== group "free-regular") awesome-free-regular-dict)
    ((== group "free-solid") awesome-free-solid-dict)
    (else '(()))))

(define (get-glyph name l)
  (if (nnull? l)
    (let ((g (assoc name (caar l))))
       (if g (cons (cdar l) (cdr g)) (get-glyph name (cdr l))))
    '()))

(tm-define (awesome-glyph name size) 
  (:secure #t)
  (let ((x (get-glyph (tree->stree name) (groups))))
    (stree->tree  (if (nnull? x)
        `(with "font" ,(car x) "font-size" ,size ,(cdr x))
        "[unknown symbol]"))))

(define (make-list l a)
  (if (nnull? l) (make-list (cdr l) (cons `(aw-entry (aw ,(caar l) "1.0") ,(caar l)) a))
     `(document ,@(reverse a))))

(tm-define (aw-list group)
  (:secure #t)
  (stree->tree (make-list (filter 
          (lambda (x) (!= (car x) "font-awesome-logo-full")) 
            (get-dict (tree->stree group))) '())))

(define (make-table l n a)
  (if (nnull? l)
    (let* ((name (car (car l)))
            (r `((cell (document ,name)) (cell (document (aw ,name "1.0"))))))
      (if (< n 2)
          (make-table (cdr l) (+ n 1) (cons (append r (car a)) (cdr a)))
          (make-table (cdr l) 0 (cons '() (cons (cons 'row (reverse (append r (car a)))) (cdr a))))))
    (cons 'table (cdr (reverse 
         (if (null? (car a)) 
               (cdr a) 
               (cons (cons 'row (reverse (car a))) (cdr a))))))))

;; not working well
(tm-define (aw-all-table group)
  (:secure #t)
  (stree->tree `(wide-tabular 
    (document (tformat (twith "table-hyphen" "y")
 (cwith "1" "-1" "1" "1" "cell-width" "2em") 
 (cwith "1" "-1" "1" "1" "cell-hmode" "exact") 
 (cwith "1" "-1" "3" "3" "cell-width" "2em") 
 (cwith "1" "-1" "3" "3" "cell-hmode" "exact") 
 (cwith "1" "-1" "5" "5" "cell-width" "2em") 
 (cwith "1" "-1" "5" "5" "cell-hmode" "exact") 
 (cwith "1" "-1" "1" "1" "cell-halign" "c") 
 (cwith "1" "-1" "3" "3" "cell-halign" "c") 
 (cwith "1" "-1" "5" "5" "cell-halign" "c") 
      ,(make-table (filter 
          (lambda (x) (!= (car x) "font-awesome-logo-full")) (get-dict (tree->stree group))) 0 '(())))))))


; awk 'BEGIN{i=1}{if ((i%3) == 0) ORS="\n"; else ORS="\t"; i++; sub("0x","",$1); print "    ( \""$2"\" . \"<#" $1 ">\")"}'

(define awesome-brands-dict '(
       ( "twitter-square" . "<#F081>")	    ( "facebook-square" . "<#F082>")	    ( "linkedin" . "<#F08C>")
    ( "github-square" . "<#F092>")	    ( "twitter" . "<#F099>")	    ( "facebook" . "<#F09A>")
    ( "github" . "<#F09B>")	    ( "pinterest" . "<#F0D2>")	    ( "pinterest-square" . "<#F0D3>")
    ( "google-plus-square" . "<#F0D4>")	    ( "google-plus-g" . "<#F0D5>")	    ( "linkedin-in" . "<#F0E1>")
    ( "github-alt" . "<#F113>")	    ( "maxcdn" . "<#F136>")	    ( "html5" . "<#F13B>")
    ( "css3" . "<#F13C>")	    ( "btc" . "<#F15A>")	    ( "youtube" . "<#F167>")
    ( "xing" . "<#F168>")	    ( "xing-square" . "<#F169>")	    ( "dropbox" . "<#F16B>")
    ( "stack-overflow" . "<#F16C>")	    ( "instagram" . "<#F16D>")	    ( "flickr" . "<#F16E>")
    ( "adn" . "<#F170>")	    ( "bitbucket" . "<#F171>")	    ( "tumblr" . "<#F173>")
    ( "tumblr-square" . "<#F174>")	    ( "apple" . "<#F179>")	    ( "windows" . "<#F17A>")
    ( "android" . "<#F17B>")	    ( "linux" . "<#F17C>")	    ( "dribbble" . "<#F17D>")
    ( "skype" . "<#F17E>")	    ( "foursquare" . "<#F180>")	    ( "trello" . "<#F181>")
    ( "gratipay" . "<#F184>")	    ( "vk" . "<#F189>")	    ( "weibo" . "<#F18A>")
    ( "renren" . "<#F18B>")	    ( "pagelines" . "<#F18C>")	    ( "stack-exchange" . "<#F18D>")
    ( "vimeo-square" . "<#F194>")	    ( "slack" . "<#F198>")	    ( "wordpress" . "<#F19A>")
    ( "openid" . "<#F19B>")	    ( "yahoo" . "<#F19E>")	    ( "google" . "<#F1A0>")
    ( "reddit" . "<#F1A1>")	    ( "reddit-square" . "<#F1A2>")	    ( "stumbleupon-circle" . "<#F1A3>")
    ( "stumbleupon" . "<#F1A4>")	    ( "delicious" . "<#F1A5>")	    ( "digg" . "<#F1A6>")
    ( "pied-piper-pp" . "<#F1A7>")	    ( "pied-piper-alt" . "<#F1A8>")	    ( "drupal" . "<#F1A9>")
    ( "joomla" . "<#F1AA>")	    ( "behance" . "<#F1B4>")	    ( "behance-square" . "<#F1B5>")
    ( "steam" . "<#F1B6>")	    ( "steam-square" . "<#F1B7>")	    ( "spotify" . "<#F1BC>")
    ( "deviantart" . "<#F1BD>")	    ( "soundcloud" . "<#F1BE>")	    ( "vine" . "<#F1CA>")
    ( "codepen" . "<#F1CB>")	    ( "jsfiddle" . "<#F1CC>")	    ( "rebel" . "<#F1D0>")
    ( "empire" . "<#F1D1>")	    ( "git-square" . "<#F1D2>")	    ( "git" . "<#F1D3>")
    ( "hacker-news" . "<#F1D4>")	    ( "tencent-weibo" . "<#F1D5>")	    ( "qq" . "<#F1D6>")
    ( "weixin" . "<#F1D7>")	    ( "slideshare" . "<#F1E7>")	    ( "twitch" . "<#F1E8>")
    ( "yelp" . "<#F1E9>")	    ( "paypal" . "<#F1ED>")	    ( "google-wallet" . "<#F1EE>")
    ( "cc-visa" . "<#F1F0>")	    ( "cc-mastercard" . "<#F1F1>")	    ( "cc-discover" . "<#F1F2>")
    ( "cc-amex" . "<#F1F3>")	    ( "cc-paypal" . "<#F1F4>")	    ( "cc-stripe" . "<#F1F5>")
    ( "lastfm" . "<#F202>")	    ( "lastfm-square" . "<#F203>")	    ( "ioxhost" . "<#F208>")
    ( "angellist" . "<#F209>")	    ( "buysellads" . "<#F20D>")	    ( "connectdevelop" . "<#F20E>")
    ( "dashcube" . "<#F210>")	    ( "forumbee" . "<#F211>")	    ( "leanpub" . "<#F212>")
    ( "sellsy" . "<#F213>")	    ( "shirtsinbulk" . "<#F214>")	    ( "simplybuilt" . "<#F215>")
    ( "skyatlas" . "<#F216>")	    ( "pinterest-p" . "<#F231>")	    ( "whatsapp" . "<#F232>")
    ( "viacoin" . "<#F237>")	    ( "medium" . "<#F23A>")	    ( "y-combinator" . "<#F23B>")
    ( "optin-monster" . "<#F23C>")	    ( "opencart" . "<#F23D>")	    ( "expeditedssl" . "<#F23E>")
    ( "cc-jcb" . "<#F24B>")	    ( "cc-diners-club" . "<#F24C>")	    ( "creative-commons" . "<#F25E>")
    ( "gg" . "<#F260>")	    ( "gg-circle" . "<#F261>")	    ( "tripadvisor" . "<#F262>")
    ( "odnoklassniki" . "<#F263>")	    ( "odnoklassniki-square" . "<#F264>")	    ( "get-pocket" . "<#F265>")
    ( "wikipedia-w" . "<#F266>")	    ( "safari" . "<#F267>")	    ( "chrome" . "<#F268>")
    ( "firefox" . "<#F269>")	    ( "opera" . "<#F26A>")	    ( "internet-explorer" . "<#F26B>")
    ( "contao" . "<#F26D>")	    ( "500px" . "<#F26E>")	    ( "amazon" . "<#F270>")
    ( "houzz" . "<#F27C>")	    ( "vimeo-v" . "<#F27D>")	    ( "black-tie" . "<#F27E>")
    ( "fonticons" . "<#F280>")	    ( "reddit-alien" . "<#F281>")	    ( "edge" . "<#F282>")
    ( "codiepie" . "<#F284>")	    ( "modx" . "<#F285>")	    ( "fort-awesome" . "<#F286>")
    ( "usb" . "<#F287>")	    ( "product-hunt" . "<#F288>")	    ( "mixcloud" . "<#F289>")
    ( "scribd" . "<#F28A>")	    ( "bluetooth" . "<#F293>")	    ( "bluetooth-b" . "<#F294>")
    ( "gitlab" . "<#F296>")	    ( "wpbeginner" . "<#F297>")	    ( "wpforms" . "<#F298>")
    ( "envira" . "<#F299>")	    ( "glide" . "<#F2A5>")	    ( "glide-g" . "<#F2A6>")
    ( "viadeo" . "<#F2A9>")	    ( "viadeo-square" . "<#F2AA>")	    ( "snapchat" . "<#F2AB>")
    ( "snapchat-ghost" . "<#F2AC>")	    ( "snapchat-square" . "<#F2AD>")	    ( "pied-piper" . "<#F2AE>")
    ( "first-order" . "<#F2B0>")	    ( "yoast" . "<#F2B1>")	    ( "themeisle" . "<#F2B2>")
    ( "google-plus" . "<#F2B3>")	    ( "font-awesome" . "<#F2B4>")	    ( "linode" . "<#F2B8>")
    ( "quora" . "<#F2C4>")	    ( "free-code-camp" . "<#F2C5>")	    ( "telegram" . "<#F2C6>")
    ( "bandcamp" . "<#F2D5>")	    ( "grav" . "<#F2D6>")	    ( "etsy" . "<#F2D7>")
    ( "imdb" . "<#F2D8>")	    ( "ravelry" . "<#F2D9>")	    ( "sellcast" . "<#F2DA>")
    ( "superpowers" . "<#F2DD>")	    ( "wpexplorer" . "<#F2DE>")	    ( "meetup" . "<#F2E0>")
    ( "font-awesome-alt" . "<#F35C>")	    ( "accessible-icon" . "<#F368>")	    ( "accusoft" . "<#F369>")
    ( "adversal" . "<#F36A>")	    ( "affiliatetheme" . "<#F36B>")	    ( "algolia" . "<#F36C>")
    ( "amilia" . "<#F36D>")	    ( "angrycreative" . "<#F36E>")	    ( "app-store" . "<#F36F>")
    ( "app-store-ios" . "<#F370>")	    ( "apper" . "<#F371>")	    ( "asymmetrik" . "<#F372>")
    ( "audible" . "<#F373>")	    ( "avianex" . "<#F374>")	    ( "aws" . "<#F375>")
    ( "bimobject" . "<#F378>")	    ( "bitcoin" . "<#F379>")	    ( "bity" . "<#F37A>")
    ( "blackberry" . "<#F37B>")	    ( "blogger" . "<#F37C>")	    ( "blogger-b" . "<#F37D>")
    ( "buromobelexperte" . "<#F37F>")	    ( "centercode" . "<#F380>")	    ( "cloudscale" . "<#F383>")
    ( "cloudsmith" . "<#F384>")	    ( "cloudversify" . "<#F385>")	    ( "cpanel" . "<#F388>")
    ( "css3-alt" . "<#F38B>")	    ( "cuttlefish" . "<#F38C>")	    ( "d-and-d" . "<#F38D>")
    ( "deploydog" . "<#F38E>")	    ( "deskpro" . "<#F38F>")	    ( "digital-ocean" . "<#F391>")
    ( "discord" . "<#F392>")	    ( "discourse" . "<#F393>")	    ( "dochub" . "<#F394>")
    ( "docker" . "<#F395>")	    ( "draft2digital" . "<#F396>")	    ( "dribbble-square" . "<#F397>")
    ( "dyalog" . "<#F399>")	    ( "earlybirds" . "<#F39A>")	    ( "erlang" . "<#F39D>")
    ( "facebook-f" . "<#F39E>")	    ( "facebook-messenger" . "<#F39F>")	    ( "firstdraft" . "<#F3A1>")
    ( "fonticons-fi" . "<#F3A2>")	    ( "fort-awesome-alt" . "<#F3A3>")	    ( "freebsd" . "<#F3A4>")
    ( "gitkraken" . "<#F3A6>")	    ( "gofore" . "<#F3A7>")	    ( "goodreads" . "<#F3A8>")
    ( "goodreads-g" . "<#F3A9>")	    ( "google-drive" . "<#F3AA>")	    ( "google-play" . "<#F3AB>")
    ( "gripfire" . "<#F3AC>")	    ( "grunt" . "<#F3AD>")	    ( "gulp" . "<#F3AE>")
    ( "hacker-news-square" . "<#F3AF>")	    ( "hire-a-helper" . "<#F3B0>")	    ( "hotjar" . "<#F3B1>")
    ( "hubspot" . "<#F3B2>")	    ( "itunes" . "<#F3B4>")	    ( "itunes-note" . "<#F3B5>")
    ( "jenkins" . "<#F3B6>")	    ( "joget" . "<#F3B7>")	    ( "js" . "<#F3B8>")
    ( "js-square" . "<#F3B9>")	    ( "keycdn" . "<#F3BA>")	    ( "kickstarter" . "<#F3BB>")
    ( "kickstarter-k" . "<#F3BC>")	    ( "laravel" . "<#F3BD>")	    ( "line" . "<#F3C0>")
    ( "lyft" . "<#F3C3>")	    ( "magento" . "<#F3C4>")	    ( "medapps" . "<#F3C6>")
    ( "medium-m" . "<#F3C7>")	    ( "medrt" . "<#F3C8>")	    ( "microsoft" . "<#F3CA>")
    ( "mix" . "<#F3CB>")	    ( "mizuni" . "<#F3CC>")	    ( "monero" . "<#F3D0>")
    ( "napster" . "<#F3D2>")	    ( "node-js" . "<#F3D3>")	    ( "npm" . "<#F3D4>")
    ( "ns8" . "<#F3D5>")	    ( "nutritionix" . "<#F3D6>")	    ( "page4" . "<#F3D7>")
    ( "palfed" . "<#F3D8>")	    ( "patreon" . "<#F3D9>")	    ( "periscope" . "<#F3DA>")
    ( "phabricator" . "<#F3DB>")	    ( "phoenix-framework" . "<#F3DC>")	    ( "playstation" . "<#F3DF>")
    ( "pushed" . "<#F3E1>")	    ( "python" . "<#F3E2>")	    ( "red-river" . "<#F3E3>")
    ( "wpressr" . "<#F3E4>")	    ( "replyd" . "<#F3E6>")	    ( "resolving" . "<#F3E7>")
    ( "rocketchat" . "<#F3E8>")	    ( "rockrms" . "<#F3E9>")	    ( "schlix" . "<#F3EA>")
    ( "searchengin" . "<#F3EB>")	    ( "servicestack" . "<#F3EC>")	    ( "sistrix" . "<#F3EE>")
    ( "slack-hash" . "<#F3EF>")	    ( "speakap" . "<#F3F3>")	    ( "staylinked" . "<#F3F5>")
    ( "steam-symbol" . "<#F3F6>")	    ( "sticker-mule" . "<#F3F7>")	    ( "studiovinari" . "<#F3F8>")
    ( "supple" . "<#F3F9>")	    ( "telegram-plane" . "<#F3FE>")	    ( "uber" . "<#F402>")
    ( "uikit" . "<#F403>")	    ( "uniregistry" . "<#F404>")	    ( "untappd" . "<#F405>")
    ( "ussunnah" . "<#F407>")	    ( "vaadin" . "<#F408>")	    ( "viber" . "<#F409>")
    ( "vimeo" . "<#F40A>")	    ( "vnv" . "<#F40B>")	    ( "whatsapp-square" . "<#F40C>")
    ( "whmcs" . "<#F40D>")	    ( "wordpress-simple" . "<#F411>")	    ( "xbox" . "<#F412>")
    ( "yandex" . "<#F413>")	    ( "yandex-international" . "<#F414>")	    ( "apple-pay" . "<#F415>")
    ( "cc-apple-pay" . "<#F416>")	    ( "fly" . "<#F417>")	    ( "nintendo-switch" . "<#F418>")
    ( "node" . "<#F419>")	    ( "osi" . "<#F41A>")	    ( "react" . "<#F41B>")
    ( "autoprefixer" . "<#F41C>")	    ( "less" . "<#F41D>")	    ( "sass" . "<#F41E>")
    ( "vuejs" . "<#F41F>")	    ( "angular" . "<#F420>")	    ( "aviato" . "<#F421>")
    ( "ember" . "<#F423>")	    ( "font-awesome-flag" . "<#F425>")	    ( "gitter" . "<#F426>")
    ( "hooli" . "<#F427>")	    ( "strava" . "<#F428>")	    ( "stripe" . "<#F429>")
    ( "stripe-s" . "<#F42A>")	    ( "typo3" . "<#F42B>")	    ( "amazon-pay" . "<#F42C>")
    ( "cc-amazon-pay" . "<#F42D>")	    ( "ethereum" . "<#F42E>")	    ( "korvue" . "<#F42F>")
    ( "elementor" . "<#F430>")	    ( "youtube-square" . "<#F431>")	    ( "flipboard" . "<#F44D>")
    ( "hips" . "<#F452>")	    ( "php" . "<#F457>")	    ( "quinscape" . "<#F459>")
    ( "readme" . "<#F4D5>")	    ( "java" . "<#F4E4>")	    ( "pied-piper-hat" . "<#F4E5>")
    ( "font-awesome-logo-full" . "<#F4E6>")	    ( "creative-commons-by" . "<#F4E7>")	    ( "creative-commons-nc" . "<#F4E8>")
    ( "creative-commons-nc-eu" . "<#F4E9>")	    ( "creative-commons-nc-jp" . "<#F4EA>")	    ( "creative-commons-nd" . "<#F4EB>")
    ( "creative-commons-pd" . "<#F4EC>")	    ( "creative-commons-pd-alt" . "<#F4ED>")	    ( "creative-commons-remix" . "<#F4EE>")
    ( "creative-commons-sa" . "<#F4EF>")	    ( "creative-commons-sampling" . "<#F4F0>")	    ( "creative-commons-sampling-plus" . "<#F4F1>")
    ( "creative-commons-share" . "<#F4F2>")	    ( "creative-commons-zero" . "<#F4F3>")	    ( "ebay" . "<#F4F4>")
    ( "keybase" . "<#F4F5>")	    ( "mastodon" . "<#F4F6>")	    ( "r-project" . "<#F4F7>")
    ( "researchgate" . "<#F4F8>")	    ( "teamspeak" . "<#F4F9>")	    ( "first-order-alt" . "<#F50A>")
    ( "fulcrum" . "<#F50B>")	    ( "galactic-republic" . "<#F50C>")	    ( "galactic-senate" . "<#F50D>")
    ( "jedi-order" . "<#F50E>")	    ( "mandalorian" . "<#F50F>")	    ( "old-republic" . "<#F510>")
    ( "phoenix-squadron" . "<#F511>")	    ( "sith" . "<#F512>")	    ( "trade-federation" . "<#F513>")
    ( "wolf-pack-battalion" . "<#F514>")	    ( "hornbill" . "<#F592>")	    ( "mailchimp" . "<#F59E>")
    ( "megaport" . "<#F5A3>")	    ( "nimblr" . "<#F5A8>")	    ( "rev" . "<#F5B2>")
    ( "shopware" . "<#F5B5>")	    ( "squarespace" . "<#F5BE>")	    ( "themeco" . "<#F5C6>")
    ( "weebly" . "<#F5CC>")	    ( "wix" . "<#F5CF>")	    ( "ello" . "<#F5F1>")
    ( "hackerrank" . "<#F5F7>")	    ( "kaggle" . "<#F5FA>")	    ( "markdown" . "<#F60F>")
    ( "neos" . "<#F612>")	    ( "zhihu" . "<#F63F>")	    ( "alipay" . "<#F642>")
    ( "the-red-yeti" . "<#F69D>")	    ( "acquisitions-incorporated" . "<#F6AF>")	    ( "critical-role" . "<#F6C9>")
    ( "d-and-d-beyond" . "<#F6CA>")	    ( "dev" . "<#F6CC>")	    ( "fantasy-flight-games" . "<#F6DC>")
    ( "penny-arcade" . "<#F704>")	    ( "wizards-of-the-coast" . "<#F730>")	    ( "think-peaks" . "<#F731>")
    ( "reacteurope" . "<#F75D>")	    ( "adobe" . "<#F778>")	    ( "artstation" . "<#F77A>")
    ( "atlassian" . "<#F77B>")	    ( "canadian-maple-leaf" . "<#F785>")	    ( "centos" . "<#F789>")
    ( "confluence" . "<#F78D>")	    ( "dhl" . "<#F790>")	    ( "diaspora" . "<#F791>")
    ( "fedex" . "<#F797>")	    ( "fedora" . "<#F798>")	    ( "figma" . "<#F799>")
    ( "intercom" . "<#F7AF>")	    ( "invision" . "<#F7B0>")	    ( "jira" . "<#F7B1>")
    ( "mendeley" . "<#F7B3>")	    ( "raspberry-pi" . "<#F7BB>")	    ( "redhat" . "<#F7BC>")
    ( "sketch" . "<#F7C6>")	    ( "sourcetree" . "<#F7D3>")	    ( "suse" . "<#F7D6>")
    ( "ubuntu" . "<#F7DF>")	    ( "ups" . "<#F7E0>")	    ( "usps" . "<#F7E1>")
    ( "yarn" . "<#F7E3>")	    ( "airbnb" . "<#F834>")	    ( "battle-net" . "<#F835>")
    ( "bootstrap" . "<#F836>")	    ( "buffer" . "<#F837>")	    ( "chromecast" . "<#F838>")
    ( "evernote" . "<#F839>")	    ( "itch-io" . "<#F83A>")	    ( "salesforce" . "<#F83B>")
    ( "speaker-deck" . "<#F83C>")	    ( "symfony" . "<#F83D>")	    ( "waze" . "<#F83F>")
    ( "yammer" . "<#F840>")
))


(define awesome-free-regular-dict '(
  ( "heart" . "<#F004>")	    ( "star" . "<#F005>")	    ( "user" . "<#F007>")
    ( "clock" . "<#F017>")	    ( "list-alt" . "<#F022>")	    ( "flag" . "<#F024>")
    ( "bookmark" . "<#F02E>")	    ( "image" . "<#F03E>")	    ( "edit" . "<#F044>")
    ( "times-circle" . "<#F057>")	    ( "check-circle" . "<#F058>")	    ( "question-circle" . "<#F059>")
    ( "eye" . "<#F06E>")	    ( "eye-slash" . "<#F070>")	    ( "calendar-alt" . "<#F073>")
    ( "comment" . "<#F075>")	    ( "folder" . "<#F07B>")	    ( "folder-open" . "<#F07C>")
    ( "chart-bar" . "<#F080>")	    ( "comments" . "<#F086>")	    ( "star-half" . "<#F089>")
    ( "lemon" . "<#F094>")	    ( "credit-card" . "<#F09D>")	    ( "hdd" . "<#F0A0>")
    ( "hand-point-right" . "<#F0A4>")	    ( "hand-point-left" . "<#F0A5>")	    ( "hand-point-up" . "<#F0A6>")
    ( "hand-point-down" . "<#F0A7>")	    ( "copy" . "<#F0C5>")	    ( "save" . "<#F0C7>")
    ( "square" . "<#F0C8>")	    ( "envelope" . "<#F0E0>")	    ( "lightbulb" . "<#F0EB>")
    ( "bell" . "<#F0F3>")	    ( "hospital" . "<#F0F8>")	    ( "plus-square" . "<#F0FE>")
    ( "circle" . "<#F111>")	    ( "smile" . "<#F118>")	    ( "frown" . "<#F119>")
    ( "meh" . "<#F11A>")	    ( "keyboard" . "<#F11C>")	    ( "calendar" . "<#F133>")
    ( "play-circle" . "<#F144>")	    ( "minus-square" . "<#F146>")	    ( "check-square" . "<#F14A>")
    ( "share-square" . "<#F14D>")	    ( "compass" . "<#F14E>")	    ( "caret-square-down" . "<#F150>")
    ( "caret-square-up" . "<#F151>")	    ( "caret-square-right" . "<#F152>")	    ( "file" . "<#F15B>")
    ( "file-alt" . "<#F15C>")	    ( "thumbs-up" . "<#F164>")	    ( "thumbs-down" . "<#F165>")
    ( "sun" . "<#F185>")	    ( "moon" . "<#F186>")	    ( "caret-square-left" . "<#F191>")
    ( "dot-circle" . "<#F192>")	    ( "building" . "<#F1AD>")	    ( "file-pdf" . "<#F1C1>")
    ( "file-word" . "<#F1C2>")	    ( "file-excel" . "<#F1C3>")	    ( "file-powerpoint" . "<#F1C4>")
    ( "file-image" . "<#F1C5>")	    ( "file-archive" . "<#F1C6>")	    ( "file-audio" . "<#F1C7>")
    ( "file-video" . "<#F1C8>")	    ( "file-code" . "<#F1C9>")	    ( "life-ring" . "<#F1CD>")
    ( "paper-plane" . "<#F1D8>")	    ( "futbol" . "<#F1E3>")	    ( "newspaper" . "<#F1EA>")
    ( "bell-slash" . "<#F1F6>")	    ( "copyright" . "<#F1F9>")	    ( "closed-captioning" . "<#F20A>")
    ( "object-group" . "<#F247>")	    ( "object-ungroup" . "<#F248>")	    ( "sticky-note" . "<#F249>")
    ( "clone" . "<#F24D>")	    ( "hourglass" . "<#F254>")	    ( "hand-rock" . "<#F255>")
    ( "hand-paper" . "<#F256>")	    ( "hand-scissors" . "<#F257>")	    ( "hand-lizard" . "<#F258>")
    ( "hand-spock" . "<#F259>")	    ( "hand-pointer" . "<#F25A>")	    ( "hand-peace" . "<#F25B>")
    ( "registered" . "<#F25D>")	    ( "calendar-plus" . "<#F271>")	    ( "calendar-minus" . "<#F272>")
    ( "calendar-times" . "<#F273>")	    ( "calendar-check" . "<#F274>")	    ( "map" . "<#F279>")
    ( "comment-alt" . "<#F27A>")	    ( "pause-circle" . "<#F28B>")	    ( "stop-circle" . "<#F28D>")
    ( "handshake" . "<#F2B5>")	    ( "envelope-open" . "<#F2B6>")	    ( "address-book" . "<#F2B9>")
    ( "address-card" . "<#F2BB>")	    ( "user-circle" . "<#F2BD>")	    ( "id-badge" . "<#F2C1>")
    ( "id-card" . "<#F2C2>")	    ( "window-maximize" . "<#F2D0>")	    ( "window-minimize" . "<#F2D1>")
    ( "window-restore" . "<#F2D2>")	    ( "snowflake" . "<#F2DC>")	    ( "trash-alt" . "<#F2ED>")
    ( "images" . "<#F302>")	    ( "clipboard" . "<#F328>")	    ( "arrow-alt-circle-down" . "<#F358>")
    ( "arrow-alt-circle-left" . "<#F359>")	    ( "arrow-alt-circle-right" . "<#F35A>")	    ( "arrow-alt-circle-up" . "<#F35B>")
    ( "gem" . "<#F3A5>")	    ( "money-bill-alt" . "<#F3D1>")	    ( "window-close" . "<#F410>")
    ( "comment-dots" . "<#F4AD>")	    ( "smile-wink" . "<#F4DA>")	    ( "font-awesome-logo-full" . "<#F4E6>")
    ( "angry" . "<#F556>")	    ( "dizzy" . "<#F567>")	    ( "flushed" . "<#F579>")
    ( "frown-open" . "<#F57A>")	    ( "grimace" . "<#F57F>")	    ( "grin" . "<#F580>")
    ( "grin-alt" . "<#F581>")	    ( "grin-beam" . "<#F582>")	    ( "grin-beam-sweat" . "<#F583>")
    ( "grin-hearts" . "<#F584>")	    ( "grin-squint" . "<#F585>")	    ( "grin-squint-tears" . "<#F586>")
    ( "grin-stars" . "<#F587>")	    ( "grin-tears" . "<#F588>")	    ( "grin-tongue" . "<#F589>")
    ( "grin-tongue-squint" . "<#F58A>")	    ( "grin-tongue-wink" . "<#F58B>")	    ( "grin-wink" . "<#F58C>")
    ( "kiss" . "<#F596>")	    ( "kiss-beam" . "<#F597>")	    ( "kiss-wink-heart" . "<#F598>")
    ( "laugh" . "<#F599>")	    ( "laugh-beam" . "<#F59A>")	    ( "laugh-squint" . "<#F59B>")
    ( "laugh-wink" . "<#F59C>")	    ( "meh-blank" . "<#F5A4>")	    ( "meh-rolling-eyes" . "<#F5A5>")
    ( "sad-cry" . "<#F5B3>")	    ( "sad-tear" . "<#F5B4>")	    ( "smile-beam" . "<#F5B8>")
    ( "surprise" . "<#F5C2>")	    ( "tired" . "<#F5C8>")
))


(define awesome-free-solid-dict '(
  ( "glass-martini" . "<#F000>")	    ( "music" . "<#F001>")	    ( "search" . "<#F002>")
    ( "heart" . "<#F004>")	    ( "star" . "<#F005>")	    ( "user" . "<#F007>")
    ( "film" . "<#F008>")	    ( "th-large" . "<#F009>")	    ( "th" . "<#F00A>")
    ( "th-list" . "<#F00B>")	    ( "check" . "<#F00C>")	    ( "times" . "<#F00D>")
    ( "search-plus" . "<#F00E>")	    ( "search-minus" . "<#F010>")	    ( "power-off" . "<#F011>")
    ( "signal" . "<#F012>")	    ( "cog" . "<#F013>")	    ( "home" . "<#F015>")
    ( "clock" . "<#F017>")	    ( "road" . "<#F018>")	    ( "download" . "<#F019>")
    ( "inbox" . "<#F01C>")	    ( "redo" . "<#F01E>")	    ( "sync" . "<#F021>")
    ( "list-alt" . "<#F022>")	    ( "lock" . "<#F023>")	    ( "flag" . "<#F024>")
    ( "headphones" . "<#F025>")	    ( "volume-off" . "<#F026>")	    ( "volume-down" . "<#F027>")
    ( "volume-up" . "<#F028>")	    ( "qrcode" . "<#F029>")	    ( "barcode" . "<#F02A>")
    ( "tag" . "<#F02B>")	    ( "tags" . "<#F02C>")	    ( "book" . "<#F02D>")
    ( "bookmark" . "<#F02E>")	    ( "print" . "<#F02F>")	    ( "camera" . "<#F030>")
    ( "font" . "<#F031>")	    ( "bold" . "<#F032>")	    ( "italic" . "<#F033>")
    ( "text-height" . "<#F034>")	    ( "text-width" . "<#F035>")	    ( "align-left" . "<#F036>")
    ( "align-center" . "<#F037>")	    ( "align-right" . "<#F038>")	    ( "align-justify" . "<#F039>")
    ( "list" . "<#F03A>")	    ( "outdent" . "<#F03B>")	    ( "indent" . "<#F03C>")
    ( "video" . "<#F03D>")	    ( "image" . "<#F03E>")	    ( "map-marker" . "<#F041>")
    ( "adjust" . "<#F042>")	    ( "tint" . "<#F043>")	    ( "edit" . "<#F044>")
    ( "step-backward" . "<#F048>")	    ( "fast-backward" . "<#F049>")	    ( "backward" . "<#F04A>")
    ( "play" . "<#F04B>")	    ( "pause" . "<#F04C>")	    ( "stop" . "<#F04D>")
    ( "forward" . "<#F04E>")	    ( "fast-forward" . "<#F050>")	    ( "step-forward" . "<#F051>")
    ( "eject" . "<#F052>")	    ( "chevron-left" . "<#F053>")	    ( "chevron-right" . "<#F054>")
    ( "plus-circle" . "<#F055>")	    ( "minus-circle" . "<#F056>")	    ( "times-circle" . "<#F057>")
    ( "check-circle" . "<#F058>")	    ( "question-circle" . "<#F059>")	    ( "info-circle" . "<#F05A>")
    ( "crosshairs" . "<#F05B>")	    ( "ban" . "<#F05E>")	    ( "arrow-left" . "<#F060>")
    ( "arrow-right" . "<#F061>")	    ( "arrow-up" . "<#F062>")	    ( "arrow-down" . "<#F063>")
    ( "share" . "<#F064>")	    ( "expand" . "<#F065>")	    ( "compress" . "<#F066>")
    ( "plus" . "<#F067>")	    ( "minus" . "<#F068>")	    ( "asterisk" . "<#F069>")
    ( "exclamation-circle" . "<#F06A>")	    ( "gift" . "<#F06B>")	    ( "leaf" . "<#F06C>")
    ( "fire" . "<#F06D>")	    ( "eye" . "<#F06E>")	    ( "eye-slash" . "<#F070>")
    ( "exclamation-triangle" . "<#F071>")	    ( "plane" . "<#F072>")	    ( "calendar-alt" . "<#F073>")
    ( "random" . "<#F074>")	    ( "comment" . "<#F075>")	    ( "magnet" . "<#F076>")
    ( "chevron-up" . "<#F077>")	    ( "chevron-down" . "<#F078>")	    ( "retweet" . "<#F079>")
    ( "shopping-cart" . "<#F07A>")	    ( "folder" . "<#F07B>")	    ( "folder-open" . "<#F07C>")
    ( "chart-bar" . "<#F080>")	    ( "camera-retro" . "<#F083>")	    ( "key" . "<#F084>")
    ( "cogs" . "<#F085>")	    ( "comments" . "<#F086>")	    ( "star-half" . "<#F089>")
    ( "thumbtack" . "<#F08D>")	    ( "trophy" . "<#F091>")	    ( "upload" . "<#F093>")
    ( "lemon" . "<#F094>")	    ( "phone" . "<#F095>")	    ( "phone-square" . "<#F098>")
    ( "unlock" . "<#F09C>")	    ( "credit-card" . "<#F09D>")	    ( "rss" . "<#F09E>")
    ( "hdd" . "<#F0A0>")	    ( "bullhorn" . "<#F0A1>")	    ( "certificate" . "<#F0A3>")
    ( "hand-point-right" . "<#F0A4>")	    ( "hand-point-left" . "<#F0A5>")	    ( "hand-point-up" . "<#F0A6>")
    ( "hand-point-down" . "<#F0A7>")	    ( "arrow-circle-left" . "<#F0A8>")	    ( "arrow-circle-right" . "<#F0A9>")
    ( "arrow-circle-up" . "<#F0AA>")	    ( "arrow-circle-down" . "<#F0AB>")	    ( "globe" . "<#F0AC>")
    ( "wrench" . "<#F0AD>")	    ( "tasks" . "<#F0AE>")	    ( "filter" . "<#F0B0>")
    ( "briefcase" . "<#F0B1>")	    ( "arrows-alt" . "<#F0B2>")	    ( "users" . "<#F0C0>")
    ( "link" . "<#F0C1>")	    ( "cloud" . "<#F0C2>")	    ( "flask" . "<#F0C3>")
    ( "cut" . "<#F0C4>")	    ( "copy" . "<#F0C5>")	    ( "paperclip" . "<#F0C6>")
    ( "save" . "<#F0C7>")	    ( "square" . "<#F0C8>")	    ( "bars" . "<#F0C9>")
    ( "list-ul" . "<#F0CA>")	    ( "list-ol" . "<#F0CB>")	    ( "strikethrough" . "<#F0CC>")
    ( "underline" . "<#F0CD>")	    ( "table" . "<#F0CE>")	    ( "magic" . "<#F0D0>")
    ( "truck" . "<#F0D1>")	    ( "money-bill" . "<#F0D6>")	    ( "caret-down" . "<#F0D7>")
    ( "caret-up" . "<#F0D8>")	    ( "caret-left" . "<#F0D9>")	    ( "caret-right" . "<#F0DA>")
    ( "columns" . "<#F0DB>")	    ( "sort" . "<#F0DC>")	    ( "sort-down" . "<#F0DD>")
    ( "sort-up" . "<#F0DE>")	    ( "envelope" . "<#F0E0>")	    ( "undo" . "<#F0E2>")
    ( "gavel" . "<#F0E3>")	    ( "bolt" . "<#F0E7>")	    ( "sitemap" . "<#F0E8>")
    ( "umbrella" . "<#F0E9>")	    ( "paste" . "<#F0EA>")	    ( "lightbulb" . "<#F0EB>")
    ( "user-md" . "<#F0F0>")	    ( "stethoscope" . "<#F0F1>")	    ( "suitcase" . "<#F0F2>")
    ( "bell" . "<#F0F3>")	    ( "coffee" . "<#F0F4>")	    ( "hospital" . "<#F0F8>")
    ( "ambulance" . "<#F0F9>")	    ( "medkit" . "<#F0FA>")	    ( "fighter-jet" . "<#F0FB>")
    ( "beer" . "<#F0FC>")	    ( "h-square" . "<#F0FD>")	    ( "plus-square" . "<#F0FE>")
    ( "angle-double-left" . "<#F100>")	    ( "angle-double-right" . "<#F101>")	    ( "angle-double-up" . "<#F102>")
    ( "angle-double-down" . "<#F103>")	    ( "angle-left" . "<#F104>")	    ( "angle-right" . "<#F105>")
    ( "angle-up" . "<#F106>")	    ( "angle-down" . "<#F107>")	    ( "desktop" . "<#F108>")
    ( "laptop" . "<#F109>")	    ( "tablet" . "<#F10A>")	    ( "mobile" . "<#F10B>")
    ( "quote-left" . "<#F10D>")	    ( "quote-right" . "<#F10E>")	    ( "spinner" . "<#F110>")
    ( "circle" . "<#F111>")	    ( "smile" . "<#F118>")	    ( "frown" . "<#F119>")
    ( "meh" . "<#F11A>")	    ( "gamepad" . "<#F11B>")	    ( "keyboard" . "<#F11C>")
    ( "flag-checkered" . "<#F11E>")	    ( "terminal" . "<#F120>")	    ( "code" . "<#F121>")
    ( "reply-all" . "<#F122>")	    ( "location-arrow" . "<#F124>")	    ( "crop" . "<#F125>")
    ( "code-branch" . "<#F126>")	    ( "unlink" . "<#F127>")	    ( "question" . "<#F128>")
    ( "info" . "<#F129>")	    ( "exclamation" . "<#F12A>")	    ( "superscript" . "<#F12B>")
    ( "subscript" . "<#F12C>")	    ( "eraser" . "<#F12D>")	    ( "puzzle-piece" . "<#F12E>")
    ( "microphone" . "<#F130>")	    ( "microphone-slash" . "<#F131>")	    ( "calendar" . "<#F133>")
    ( "fire-extinguisher" . "<#F134>")	    ( "rocket" . "<#F135>")	    ( "chevron-circle-left" . "<#F137>")
    ( "chevron-circle-right" . "<#F138>")	    ( "chevron-circle-up" . "<#F139>")	    ( "chevron-circle-down" . "<#F13A>")
    ( "anchor" . "<#F13D>")	    ( "unlock-alt" . "<#F13E>")	    ( "bullseye" . "<#F140>")
    ( "ellipsis-h" . "<#F141>")	    ( "ellipsis-v" . "<#F142>")	    ( "rss-square" . "<#F143>")
    ( "play-circle" . "<#F144>")	    ( "minus-square" . "<#F146>")	    ( "check-square" . "<#F14A>")
    ( "pen-square" . "<#F14B>")	    ( "share-square" . "<#F14D>")	    ( "compass" . "<#F14E>")
    ( "caret-square-down" . "<#F150>")	    ( "caret-square-up" . "<#F151>")	    ( "caret-square-right" . "<#F152>")
    ( "euro-sign" . "<#F153>")	    ( "pound-sign" . "<#F154>")	    ( "dollar-sign" . "<#F155>")
    ( "rupee-sign" . "<#F156>")	    ( "yen-sign" . "<#F157>")	    ( "ruble-sign" . "<#F158>")
    ( "won-sign" . "<#F159>")	    ( "file" . "<#F15B>")	    ( "file-alt" . "<#F15C>")
    ( "sort-alpha-down" . "<#F15D>")	    ( "sort-alpha-up" . "<#F15E>")	    ( "sort-amount-down" . "<#F160>")
    ( "sort-amount-up" . "<#F161>")	    ( "sort-numeric-down" . "<#F162>")	    ( "sort-numeric-up" . "<#F163>")
    ( "thumbs-up" . "<#F164>")	    ( "thumbs-down" . "<#F165>")	    ( "female" . "<#F182>")
    ( "male" . "<#F183>")	    ( "sun" . "<#F185>")	    ( "moon" . "<#F186>")
    ( "archive" . "<#F187>")	    ( "bug" . "<#F188>")	    ( "caret-square-left" . "<#F191>")
    ( "dot-circle" . "<#F192>")	    ( "wheelchair" . "<#F193>")	    ( "lira-sign" . "<#F195>")
    ( "space-shuttle" . "<#F197>")	    ( "envelope-square" . "<#F199>")	    ( "university" . "<#F19C>")
    ( "graduation-cap" . "<#F19D>")	    ( "language" . "<#F1AB>")	    ( "fax" . "<#F1AC>")
    ( "building" . "<#F1AD>")	    ( "child" . "<#F1AE>")	    ( "paw" . "<#F1B0>")
    ( "cube" . "<#F1B2>")	    ( "cubes" . "<#F1B3>")	    ( "recycle" . "<#F1B8>")
    ( "car" . "<#F1B9>")	    ( "taxi" . "<#F1BA>")	    ( "tree" . "<#F1BB>")
    ( "database" . "<#F1C0>")	    ( "file-pdf" . "<#F1C1>")	    ( "file-word" . "<#F1C2>")
    ( "file-excel" . "<#F1C3>")	    ( "file-powerpoint" . "<#F1C4>")	    ( "file-image" . "<#F1C5>")
    ( "file-archive" . "<#F1C6>")	    ( "file-audio" . "<#F1C7>")	    ( "file-video" . "<#F1C8>")
    ( "file-code" . "<#F1C9>")	    ( "life-ring" . "<#F1CD>")	    ( "circle-notch" . "<#F1CE>")
    ( "paper-plane" . "<#F1D8>")	    ( "history" . "<#F1DA>")	    ( "heading" . "<#F1DC>")
    ( "paragraph" . "<#F1DD>")	    ( "sliders-h" . "<#F1DE>")	    ( "share-alt" . "<#F1E0>")
    ( "share-alt-square" . "<#F1E1>")	    ( "bomb" . "<#F1E2>")	    ( "futbol" . "<#F1E3>")
    ( "tty" . "<#F1E4>")	    ( "binoculars" . "<#F1E5>")	    ( "plug" . "<#F1E6>")
    ( "newspaper" . "<#F1EA>")	    ( "wifi" . "<#F1EB>")	    ( "calculator" . "<#F1EC>")
    ( "bell-slash" . "<#F1F6>")	    ( "trash" . "<#F1F8>")	    ( "copyright" . "<#F1F9>")
    ( "at" . "<#F1FA>")	    ( "eye-dropper" . "<#F1FB>")	    ( "paint-brush" . "<#F1FC>")
    ( "birthday-cake" . "<#F1FD>")	    ( "chart-area" . "<#F1FE>")	    ( "chart-pie" . "<#F200>")
    ( "chart-line" . "<#F201>")	    ( "toggle-off" . "<#F204>")	    ( "toggle-on" . "<#F205>")
    ( "bicycle" . "<#F206>")	    ( "bus" . "<#F207>")	    ( "closed-captioning" . "<#F20A>")
    ( "shekel-sign" . "<#F20B>")	    ( "cart-plus" . "<#F217>")	    ( "cart-arrow-down" . "<#F218>")
    ( "ship" . "<#F21A>")	    ( "user-secret" . "<#F21B>")	    ( "motorcycle" . "<#F21C>")
    ( "street-view" . "<#F21D>")	    ( "heartbeat" . "<#F21E>")	    ( "venus" . "<#F221>")
    ( "mars" . "<#F222>")	    ( "mercury" . "<#F223>")	    ( "transgender" . "<#F224>")
    ( "transgender-alt" . "<#F225>")	    ( "venus-double" . "<#F226>")	    ( "mars-double" . "<#F227>")
    ( "venus-mars" . "<#F228>")	    ( "mars-stroke" . "<#F229>")	    ( "mars-stroke-v" . "<#F22A>")
    ( "mars-stroke-h" . "<#F22B>")	    ( "neuter" . "<#F22C>")	    ( "genderless" . "<#F22D>")
    ( "server" . "<#F233>")	    ( "user-plus" . "<#F234>")	    ( "user-times" . "<#F235>")
    ( "bed" . "<#F236>")	    ( "train" . "<#F238>")	    ( "subway" . "<#F239>")
    ( "battery-full" . "<#F240>")	    ( "battery-three-quarters" . "<#F241>")	    ( "battery-half" . "<#F242>")
    ( "battery-quarter" . "<#F243>")	    ( "battery-empty" . "<#F244>")	    ( "mouse-pointer" . "<#F245>")
    ( "i-cursor" . "<#F246>")	    ( "object-group" . "<#F247>")	    ( "object-ungroup" . "<#F248>")
    ( "sticky-note" . "<#F249>")	    ( "clone" . "<#F24D>")	    ( "balance-scale" . "<#F24E>")
    ( "hourglass-start" . "<#F251>")	    ( "hourglass-half" . "<#F252>")	    ( "hourglass-end" . "<#F253>")
    ( "hourglass" . "<#F254>")	    ( "hand-rock" . "<#F255>")	    ( "hand-paper" . "<#F256>")
    ( "hand-scissors" . "<#F257>")	    ( "hand-lizard" . "<#F258>")	    ( "hand-spock" . "<#F259>")
    ( "hand-pointer" . "<#F25A>")	    ( "hand-peace" . "<#F25B>")	    ( "trademark" . "<#F25C>")
    ( "registered" . "<#F25D>")	    ( "tv" . "<#F26C>")	    ( "calendar-plus" . "<#F271>")
    ( "calendar-minus" . "<#F272>")	    ( "calendar-times" . "<#F273>")	    ( "calendar-check" . "<#F274>")
    ( "industry" . "<#F275>")	    ( "map-pin" . "<#F276>")	    ( "map-signs" . "<#F277>")
    ( "map" . "<#F279>")	    ( "comment-alt" . "<#F27A>")	    ( "pause-circle" . "<#F28B>")
    ( "stop-circle" . "<#F28D>")	    ( "shopping-bag" . "<#F290>")	    ( "shopping-basket" . "<#F291>")
    ( "hashtag" . "<#F292>")	    ( "percent" . "<#F295>")	    ( "universal-access" . "<#F29A>")
    ( "blind" . "<#F29D>")	    ( "audio-description" . "<#F29E>")	    ( "phone-volume" . "<#F2A0>")
    ( "braille" . "<#F2A1>")	    ( "assistive-listening-systems" . "<#F2A2>")	    ( "american-sign-language-interpreting" . "<#F2A3>")
    ( "deaf" . "<#F2A4>")	    ( "sign-language" . "<#F2A7>")	    ( "low-vision" . "<#F2A8>")
    ( "handshake" . "<#F2B5>")	    ( "envelope-open" . "<#F2B6>")	    ( "address-book" . "<#F2B9>")
    ( "address-card" . "<#F2BB>")	    ( "user-circle" . "<#F2BD>")	    ( "id-badge" . "<#F2C1>")
    ( "id-card" . "<#F2C2>")	    ( "thermometer-full" . "<#F2C7>")	    ( "thermometer-three-quarters" . "<#F2C8>")
    ( "thermometer-half" . "<#F2C9>")	    ( "thermometer-quarter" . "<#F2CA>")	    ( "thermometer-empty" . "<#F2CB>")
    ( "shower" . "<#F2CC>")	    ( "bath" . "<#F2CD>")	    ( "podcast" . "<#F2CE>")
    ( "window-maximize" . "<#F2D0>")	    ( "window-minimize" . "<#F2D1>")	    ( "window-restore" . "<#F2D2>")
    ( "microchip" . "<#F2DB>")	    ( "snowflake" . "<#F2DC>")	    ( "utensil-spoon" . "<#F2E5>")
    ( "utensils" . "<#F2E7>")	    ( "undo-alt" . "<#F2EA>")	    ( "trash-alt" . "<#F2ED>")
    ( "sync-alt" . "<#F2F1>")	    ( "stopwatch" . "<#F2F2>")	    ( "sign-out-alt" . "<#F2F5>")
    ( "sign-in-alt" . "<#F2F6>")	    ( "redo-alt" . "<#F2F9>")	    ( "poo" . "<#F2FE>")
    ( "images" . "<#F302>")	    ( "pencil-alt" . "<#F303>")	    ( "pen" . "<#F304>")
    ( "pen-alt" . "<#F305>")	    ( "long-arrow-alt-down" . "<#F309>")	    ( "long-arrow-alt-left" . "<#F30A>")
    ( "long-arrow-alt-right" . "<#F30B>")	    ( "long-arrow-alt-up" . "<#F30C>")	    ( "expand-arrows-alt" . "<#F31E>")
    ( "clipboard" . "<#F328>")	    ( "arrows-alt-h" . "<#F337>")	    ( "arrows-alt-v" . "<#F338>")
    ( "arrow-alt-circle-down" . "<#F358>")	    ( "arrow-alt-circle-left" . "<#F359>")	    ( "arrow-alt-circle-right" . "<#F35A>")
    ( "arrow-alt-circle-up" . "<#F35B>")	    ( "external-link-alt" . "<#F35D>")	    ( "external-link-square-alt" . "<#F360>")
    ( "exchange-alt" . "<#F362>")	    ( "cloud-download-alt" . "<#F381>")	    ( "cloud-upload-alt" . "<#F382>")
    ( "gem" . "<#F3A5>")	    ( "level-down-alt" . "<#F3BE>")	    ( "level-up-alt" . "<#F3BF>")
    ( "lock-open" . "<#F3C1>")	    ( "map-marker-alt" . "<#F3C5>")	    ( "microphone-alt" . "<#F3C9>")
    ( "mobile-alt" . "<#F3CD>")	    ( "money-bill-alt" . "<#F3D1>")	    ( "phone-slash" . "<#F3DD>")
    ( "portrait" . "<#F3E0>")	    ( "reply" . "<#F3E5>")	    ( "shield-alt" . "<#F3ED>")
    ( "tablet-alt" . "<#F3FA>")	    ( "tachometer-alt" . "<#F3FD>")	    ( "ticket-alt" . "<#F3FF>")
    ( "user-alt" . "<#F406>")	    ( "window-close" . "<#F410>")	    ( "baseball-ball" . "<#F433>")
    ( "basketball-ball" . "<#F434>")	    ( "bowling-ball" . "<#F436>")	    ( "chess" . "<#F439>")
    ( "chess-bishop" . "<#F43A>")	    ( "chess-board" . "<#F43C>")	    ( "chess-king" . "<#F43F>")
    ( "chess-knight" . "<#F441>")	    ( "chess-pawn" . "<#F443>")	    ( "chess-queen" . "<#F445>")
    ( "chess-rook" . "<#F447>")	    ( "dumbbell" . "<#F44B>")	    ( "football-ball" . "<#F44E>")
    ( "golf-ball" . "<#F450>")	    ( "hockey-puck" . "<#F453>")	    ( "quidditch" . "<#F458>")
    ( "square-full" . "<#F45C>")	    ( "table-tennis" . "<#F45D>")	    ( "volleyball-ball" . "<#F45F>")
    ( "allergies" . "<#F461>")	    ( "band-aid" . "<#F462>")	    ( "box" . "<#F466>")
    ( "boxes" . "<#F468>")	    ( "briefcase-medical" . "<#F469>")	    ( "burn" . "<#F46A>")
    ( "capsules" . "<#F46B>")	    ( "clipboard-check" . "<#F46C>")	    ( "clipboard-list" . "<#F46D>")
    ( "diagnoses" . "<#F470>")	    ( "dna" . "<#F471>")	    ( "dolly" . "<#F472>")
    ( "dolly-flatbed" . "<#F474>")	    ( "file-medical" . "<#F477>")	    ( "file-medical-alt" . "<#F478>")
    ( "first-aid" . "<#F479>")	    ( "hospital-alt" . "<#F47D>")	    ( "hospital-symbol" . "<#F47E>")
    ( "id-card-alt" . "<#F47F>")	    ( "notes-medical" . "<#F481>")	    ( "pallet" . "<#F482>")
    ( "pills" . "<#F484>")	    ( "prescription-bottle" . "<#F485>")	    ( "prescription-bottle-alt" . "<#F486>")
    ( "procedures" . "<#F487>")	    ( "shipping-fast" . "<#F48B>")	    ( "smoking" . "<#F48D>")
    ( "syringe" . "<#F48E>")	    ( "tablets" . "<#F490>")	    ( "thermometer" . "<#F491>")
    ( "vial" . "<#F492>")	    ( "vials" . "<#F493>")	    ( "warehouse" . "<#F494>")
    ( "weight" . "<#F496>")	    ( "x-ray" . "<#F497>")	    ( "box-open" . "<#F49E>")
    ( "comment-dots" . "<#F4AD>")	    ( "comment-slash" . "<#F4B3>")	    ( "couch" . "<#F4B8>")
    ( "donate" . "<#F4B9>")	    ( "dove" . "<#F4BA>")	    ( "hand-holding" . "<#F4BD>")
    ( "hand-holding-heart" . "<#F4BE>")	    ( "hand-holding-usd" . "<#F4C0>")	    ( "hands" . "<#F4C2>")
    ( "hands-helping" . "<#F4C4>")	    ( "parachute-box" . "<#F4CD>")	    ( "people-carry" . "<#F4CE>")
    ( "piggy-bank" . "<#F4D3>")	    ( "ribbon" . "<#F4D6>")	    ( "route" . "<#F4D7>")
    ( "seedling" . "<#F4D8>")	    ( "sign" . "<#F4D9>")	    ( "smile-wink" . "<#F4DA>")
    ( "tape" . "<#F4DB>")	    ( "truck-loading" . "<#F4DE>")	    ( "truck-moving" . "<#F4DF>")
    ( "video-slash" . "<#F4E2>")	    ( "wine-glass" . "<#F4E3>")	    ( "font-awesome-logo-full" . "<#F4E6>")
    ( "user-alt-slash" . "<#F4FA>")	    ( "user-astronaut" . "<#F4FB>")	    ( "user-check" . "<#F4FC>")
    ( "user-clock" . "<#F4FD>")	    ( "user-cog" . "<#F4FE>")	    ( "user-edit" . "<#F4FF>")
    ( "user-friends" . "<#F500>")	    ( "user-graduate" . "<#F501>")	    ( "user-lock" . "<#F502>")
    ( "user-minus" . "<#F503>")	    ( "user-ninja" . "<#F504>")	    ( "user-shield" . "<#F505>")
    ( "user-slash" . "<#F506>")	    ( "user-tag" . "<#F507>")	    ( "user-tie" . "<#F508>")
    ( "users-cog" . "<#F509>")	    ( "blender" . "<#F517>")	    ( "book-open" . "<#F518>")
    ( "broadcast-tower" . "<#F519>")	    ( "broom" . "<#F51A>")	    ( "chalkboard" . "<#F51B>")
    ( "chalkboard-teacher" . "<#F51C>")	    ( "church" . "<#F51D>")	    ( "coins" . "<#F51E>")
    ( "compact-disc" . "<#F51F>")	    ( "crow" . "<#F520>")	    ( "crown" . "<#F521>")
    ( "dice" . "<#F522>")	    ( "dice-five" . "<#F523>")	    ( "dice-four" . "<#F524>")
    ( "dice-one" . "<#F525>")	    ( "dice-six" . "<#F526>")	    ( "dice-three" . "<#F527>")
    ( "dice-two" . "<#F528>")	    ( "divide" . "<#F529>")	    ( "door-closed" . "<#F52A>")
    ( "door-open" . "<#F52B>")	    ( "equals" . "<#F52C>")	    ( "feather" . "<#F52D>")
    ( "frog" . "<#F52E>")	    ( "gas-pump" . "<#F52F>")	    ( "glasses" . "<#F530>")
    ( "greater-than" . "<#F531>")	    ( "greater-than-equal" . "<#F532>")	    ( "helicopter" . "<#F533>")
    ( "infinity" . "<#F534>")	    ( "kiwi-bird" . "<#F535>")	    ( "less-than" . "<#F536>")
    ( "less-than-equal" . "<#F537>")	    ( "memory" . "<#F538>")	    ( "microphone-alt-slash" . "<#F539>")
    ( "money-bill-wave" . "<#F53A>")	    ( "money-bill-wave-alt" . "<#F53B>")	    ( "money-check" . "<#F53C>")
    ( "money-check-alt" . "<#F53D>")	    ( "not-equal" . "<#F53E>")	    ( "palette" . "<#F53F>")
    ( "parking" . "<#F540>")	    ( "percentage" . "<#F541>")	    ( "project-diagram" . "<#F542>")
    ( "receipt" . "<#F543>")	    ( "robot" . "<#F544>")	    ( "ruler" . "<#F545>")
    ( "ruler-combined" . "<#F546>")	    ( "ruler-horizontal" . "<#F547>")	    ( "ruler-vertical" . "<#F548>")
    ( "school" . "<#F549>")	    ( "screwdriver" . "<#F54A>")	    ( "shoe-prints" . "<#F54B>")
    ( "skull" . "<#F54C>")	    ( "smoking-ban" . "<#F54D>")	    ( "store" . "<#F54E>")
    ( "store-alt" . "<#F54F>")	    ( "stream" . "<#F550>")	    ( "stroopwafel" . "<#F551>")
    ( "toolbox" . "<#F552>")	    ( "tshirt" . "<#F553>")	    ( "walking" . "<#F554>")
    ( "wallet" . "<#F555>")	    ( "angry" . "<#F556>")	    ( "archway" . "<#F557>")
    ( "atlas" . "<#F558>")	    ( "award" . "<#F559>")	    ( "backspace" . "<#F55A>")
    ( "bezier-curve" . "<#F55B>")	    ( "bong" . "<#F55C>")	    ( "brush" . "<#F55D>")
    ( "bus-alt" . "<#F55E>")	    ( "cannabis" . "<#F55F>")	    ( "check-double" . "<#F560>")
    ( "cocktail" . "<#F561>")	    ( "concierge-bell" . "<#F562>")	    ( "cookie" . "<#F563>")
    ( "cookie-bite" . "<#F564>")	    ( "crop-alt" . "<#F565>")	    ( "digital-tachograph" . "<#F566>")
    ( "dizzy" . "<#F567>")	    ( "drafting-compass" . "<#F568>")	    ( "drum" . "<#F569>")
    ( "drum-steelpan" . "<#F56A>")	    ( "feather-alt" . "<#F56B>")	    ( "file-contract" . "<#F56C>")
    ( "file-download" . "<#F56D>")	    ( "file-export" . "<#F56E>")	    ( "file-import" . "<#F56F>")
    ( "file-invoice" . "<#F570>")	    ( "file-invoice-dollar" . "<#F571>")	    ( "file-prescription" . "<#F572>")
    ( "file-signature" . "<#F573>")	    ( "file-upload" . "<#F574>")	    ( "fill" . "<#F575>")
    ( "fill-drip" . "<#F576>")	    ( "fingerprint" . "<#F577>")	    ( "fish" . "<#F578>")
    ( "flushed" . "<#F579>")	    ( "frown-open" . "<#F57A>")	    ( "glass-martini-alt" . "<#F57B>")
    ( "globe-africa" . "<#F57C>")	    ( "globe-americas" . "<#F57D>")	    ( "globe-asia" . "<#F57E>")
    ( "grimace" . "<#F57F>")	    ( "grin" . "<#F580>")	    ( "grin-alt" . "<#F581>")
    ( "grin-beam" . "<#F582>")	    ( "grin-beam-sweat" . "<#F583>")	    ( "grin-hearts" . "<#F584>")
    ( "grin-squint" . "<#F585>")	    ( "grin-squint-tears" . "<#F586>")	    ( "grin-stars" . "<#F587>")
    ( "grin-tears" . "<#F588>")	    ( "grin-tongue" . "<#F589>")	    ( "grin-tongue-squint" . "<#F58A>")
    ( "grin-tongue-wink" . "<#F58B>")	    ( "grin-wink" . "<#F58C>")	    ( "grip-horizontal" . "<#F58D>")
    ( "grip-vertical" . "<#F58E>")	    ( "headphones-alt" . "<#F58F>")	    ( "headset" . "<#F590>")
    ( "highlighter" . "<#F591>")	    ( "hot-tub" . "<#F593>")	    ( "hotel" . "<#F594>")
    ( "joint" . "<#F595>")	    ( "kiss" . "<#F596>")	    ( "kiss-beam" . "<#F597>")
    ( "kiss-wink-heart" . "<#F598>")	    ( "laugh" . "<#F599>")	    ( "laugh-beam" . "<#F59A>")
    ( "laugh-squint" . "<#F59B>")	    ( "laugh-wink" . "<#F59C>")	    ( "luggage-cart" . "<#F59D>")
    ( "map-marked" . "<#F59F>")	    ( "map-marked-alt" . "<#F5A0>")	    ( "marker" . "<#F5A1>")
    ( "medal" . "<#F5A2>")	    ( "meh-blank" . "<#F5A4>")	    ( "meh-rolling-eyes" . "<#F5A5>")
    ( "monument" . "<#F5A6>")	    ( "mortar-pestle" . "<#F5A7>")	    ( "paint-roller" . "<#F5AA>")
    ( "passport" . "<#F5AB>")	    ( "pen-fancy" . "<#F5AC>")	    ( "pen-nib" . "<#F5AD>")
    ( "pencil-ruler" . "<#F5AE>")	    ( "plane-arrival" . "<#F5AF>")	    ( "plane-departure" . "<#F5B0>")
    ( "prescription" . "<#F5B1>")	    ( "sad-cry" . "<#F5B3>")	    ( "sad-tear" . "<#F5B4>")
    ( "shuttle-van" . "<#F5B6>")	    ( "signature" . "<#F5B7>")	    ( "smile-beam" . "<#F5B8>")
    ( "solar-panel" . "<#F5BA>")	    ( "spa" . "<#F5BB>")	    ( "splotch" . "<#F5BC>")
    ( "spray-can" . "<#F5BD>")	    ( "stamp" . "<#F5BF>")	    ( "star-half-alt" . "<#F5C0>")
    ( "suitcase-rolling" . "<#F5C1>")	    ( "surprise" . "<#F5C2>")	    ( "swatchbook" . "<#F5C3>")
    ( "swimmer" . "<#F5C4>")	    ( "swimming-pool" . "<#F5C5>")	    ( "tint-slash" . "<#F5C7>")
    ( "tired" . "<#F5C8>")	    ( "tooth" . "<#F5C9>")	    ( "umbrella-beach" . "<#F5CA>")
    ( "vector-square" . "<#F5CB>")	    ( "weight-hanging" . "<#F5CD>")	    ( "wine-glass-alt" . "<#F5CE>")
    ( "air-freshener" . "<#F5D0>")	    ( "apple-alt" . "<#F5D1>")	    ( "atom" . "<#F5D2>")
    ( "bone" . "<#F5D7>")	    ( "book-reader" . "<#F5DA>")	    ( "brain" . "<#F5DC>")
    ( "car-alt" . "<#F5DE>")	    ( "car-battery" . "<#F5DF>")	    ( "car-crash" . "<#F5E1>")
    ( "car-side" . "<#F5E4>")	    ( "charging-station" . "<#F5E7>")	    ( "directions" . "<#F5EB>")
    ( "draw-polygon" . "<#F5EE>")	    ( "laptop-code" . "<#F5FC>")	    ( "layer-group" . "<#F5FD>")
    ( "microscope" . "<#F610>")	    ( "oil-can" . "<#F613>")	    ( "poop" . "<#F619>")
    ( "shapes" . "<#F61F>")	    ( "star-of-life" . "<#F621>")	    ( "teeth" . "<#F62E>")
    ( "teeth-open" . "<#F62F>")	    ( "theater-masks" . "<#F630>")	    ( "traffic-light" . "<#F637>")
    ( "truck-monster" . "<#F63B>")	    ( "truck-pickup" . "<#F63C>")	    ( "ad" . "<#F641>")
    ( "ankh" . "<#F644>")	    ( "bible" . "<#F647>")	    ( "business-time" . "<#F64A>")
    ( "city" . "<#F64F>")	    ( "comment-dollar" . "<#F651>")	    ( "comments-dollar" . "<#F653>")
    ( "cross" . "<#F654>")	    ( "dharmachakra" . "<#F655>")	    ( "envelope-open-text" . "<#F658>")
    ( "folder-minus" . "<#F65D>")	    ( "folder-plus" . "<#F65E>")	    ( "funnel-dollar" . "<#F662>")
    ( "gopuram" . "<#F664>")	    ( "hamsa" . "<#F665>")	    ( "haykal" . "<#F666>")
    ( "jedi" . "<#F669>")	    ( "journal-whills" . "<#F66A>")	    ( "kaaba" . "<#F66B>")
    ( "khanda" . "<#F66D>")	    ( "landmark" . "<#F66F>")	    ( "mail-bulk" . "<#F674>")
    ( "menorah" . "<#F676>")	    ( "mosque" . "<#F678>")	    ( "om" . "<#F679>")
    ( "pastafarianism" . "<#F67B>")	    ( "peace" . "<#F67C>")	    ( "place-of-worship" . "<#F67F>")
    ( "poll" . "<#F681>")	    ( "poll-h" . "<#F682>")	    ( "pray" . "<#F683>")
    ( "praying-hands" . "<#F684>")	    ( "quran" . "<#F687>")	    ( "search-dollar" . "<#F688>")
    ( "search-location" . "<#F689>")	    ( "socks" . "<#F696>")	    ( "square-root-alt" . "<#F698>")
    ( "star-and-crescent" . "<#F699>")	    ( "star-of-david" . "<#F69A>")	    ( "synagogue" . "<#F69B>")
    ( "torah" . "<#F6A0>")	    ( "torii-gate" . "<#F6A1>")	    ( "vihara" . "<#F6A7>")
    ( "volume-mute" . "<#F6A9>")	    ( "yin-yang" . "<#F6AD>")	    ( "blender-phone" . "<#F6B6>")
    ( "book-dead" . "<#F6B7>")	    ( "campground" . "<#F6BB>")	    ( "cat" . "<#F6BE>")
    ( "chair" . "<#F6C0>")	    ( "cloud-moon" . "<#F6C3>")	    ( "cloud-sun" . "<#F6C4>")
    ( "dice-d20" . "<#F6CF>")	    ( "dice-d6" . "<#F6D1>")	    ( "dog" . "<#F6D3>")
    ( "dragon" . "<#F6D5>")	    ( "drumstick-bite" . "<#F6D7>")	    ( "dungeon" . "<#F6D9>")
    ( "file-csv" . "<#F6DD>")	    ( "fist-raised" . "<#F6DE>")	    ( "ghost" . "<#F6E2>")
    ( "hammer" . "<#F6E3>")	    ( "hanukiah" . "<#F6E6>")	    ( "hat-wizard" . "<#F6E8>")
    ( "hiking" . "<#F6EC>")	    ( "hippo" . "<#F6ED>")	    ( "horse" . "<#F6F0>")
    ( "house-damage" . "<#F6F1>")	    ( "hryvnia" . "<#F6F2>")	    ( "mask" . "<#F6FA>")
    ( "mountain" . "<#F6FC>")	    ( "network-wired" . "<#F6FF>")	    ( "otter" . "<#F700>")
    ( "ring" . "<#F70B>")	    ( "running" . "<#F70C>")	    ( "scroll" . "<#F70E>")
    ( "skull-crossbones" . "<#F714>")	    ( "slash" . "<#F715>")	    ( "spider" . "<#F717>")
    ( "toilet-paper" . "<#F71E>")	    ( "tractor" . "<#F722>")	    ( "user-injured" . "<#F728>")
    ( "vr-cardboard" . "<#F729>")	    ( "wind" . "<#F72E>")	    ( "wine-bottle" . "<#F72F>")
    ( "cloud-meatball" . "<#F73B>")	    ( "cloud-moon-rain" . "<#F73C>")	    ( "cloud-rain" . "<#F73D>")
    ( "cloud-showers-heavy" . "<#F740>")	    ( "cloud-sun-rain" . "<#F743>")	    ( "democrat" . "<#F747>")
    ( "flag-usa" . "<#F74D>")	    ( "meteor" . "<#F753>")	    ( "person-booth" . "<#F756>")
    ( "poo-storm" . "<#F75A>")	    ( "rainbow" . "<#F75B>")	    ( "republican" . "<#F75E>")
    ( "smog" . "<#F75F>")	    ( "temperature-high" . "<#F769>")	    ( "temperature-low" . "<#F76B>")
    ( "vote-yea" . "<#F772>")	    ( "water" . "<#F773>")	    ( "baby" . "<#F77C>")
    ( "baby-carriage" . "<#F77D>")	    ( "biohazard" . "<#F780>")	    ( "blog" . "<#F781>")
    ( "calendar-day" . "<#F783>")	    ( "calendar-week" . "<#F784>")	    ( "candy-cane" . "<#F786>")
    ( "carrot" . "<#F787>")	    ( "cash-register" . "<#F788>")	    ( "compress-arrows-alt" . "<#F78C>")
    ( "dumpster" . "<#F793>")	    ( "dumpster-fire" . "<#F794>")	    ( "ethernet" . "<#F796>")
    ( "gifts" . "<#F79C>")	    ( "glass-cheers" . "<#F79F>")	    ( "glass-whiskey" . "<#F7A0>")
    ( "globe-europe" . "<#F7A2>")	    ( "grip-lines" . "<#F7A4>")	    ( "grip-lines-vertical" . "<#F7A5>")
    ( "guitar" . "<#F7A6>")	    ( "heart-broken" . "<#F7A9>")	    ( "holly-berry" . "<#F7AA>")
    ( "horse-head" . "<#F7AB>")	    ( "icicles" . "<#F7AD>")	    ( "igloo" . "<#F7AE>")
    ( "mitten" . "<#F7B5>")	    ( "mug-hot" . "<#F7B6>")	    ( "radiation" . "<#F7B9>")
    ( "radiation-alt" . "<#F7BA>")	    ( "restroom" . "<#F7BD>")	    ( "satellite" . "<#F7BF>")
    ( "satellite-dish" . "<#F7C0>")	    ( "sd-card" . "<#F7C2>")	    ( "sim-card" . "<#F7C4>")
    ( "skating" . "<#F7C5>")	    ( "skiing" . "<#F7C9>")	    ( "skiing-nordic" . "<#F7CA>")
    ( "sleigh" . "<#F7CC>")	    ( "sms" . "<#F7CD>")	    ( "snowboarding" . "<#F7CE>")
    ( "snowman" . "<#F7D0>")	    ( "snowplow" . "<#F7D2>")	    ( "tenge" . "<#F7D7>")
    ( "toilet" . "<#F7D8>")	    ( "tools" . "<#F7D9>")	    ( "tram" . "<#F7DA>")
    ( "fire-alt" . "<#F7E4>")	    ( "bacon" . "<#F7E5>")	    ( "book-medical" . "<#F7E6>")
    ( "bread-slice" . "<#F7EC>")	    ( "cheese" . "<#F7EF>")	    ( "clinic-medical" . "<#F7F2>")
    ( "comment-medical" . "<#F7F5>")	    ( "crutch" . "<#F7F7>")	    ( "egg" . "<#F7FB>")
    ( "hamburger" . "<#F805>")	    ( "hand-middle-finger" . "<#F806>")	    ( "hard-hat" . "<#F807>")
    ( "hotdog" . "<#F80F>")	    ( "ice-cream" . "<#F810>")	    ( "laptop-medical" . "<#F812>")
    ( "pager" . "<#F815>")	    ( "pepper-hot" . "<#F816>")	    ( "pizza-slice" . "<#F818>")
    ( "trash-restore" . "<#F829>")	    ( "trash-restore-alt" . "<#F82A>")	    ( "user-nurse" . "<#F82F>")
    ( "wave-square" . "<#F83E>")
))

